const mongoose=require('mongoose')
const lbSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    edition:{
        type:Number
    },
    rating:{
        type:Number,
        default:2.5
    },
    status:{
        type:String,
        default:"Available"
    },
    nextAvail:{
        type:String
    },
    charge:{
        type:Number,
        default:0
    },
    city:{
        type:String,
        required:true
    },
    pincode:{
        type:Number,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    lendBy:{
        type:String,
        required:true
    },
    author:{
        type:String
    },
    genre:{
        type:String
    },
    bookId:{
        type:String
    },
    lat:{
        type:Number
    },
    lng:{
        type:Number
    },
    image:{
        type:Buffer
    }

},{timestamps:true});
const lb=mongoose.model('lb',lbSchema);
module.exports=lb;
